//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.30 at 04:05:04 PM MSK 
//


package ru.slayter.stock.advisor.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modules" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="database" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reports" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pool">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="timeouts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="onetask" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="awaitTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modules",
    "database",
    "reports",
    "pool"
})
@XmlRootElement(name = "configuration")
public class Configuration {

    @XmlElement(required = true)
    protected String modules;
    @XmlElement(required = true)
    protected String database;
    @XmlElement(required = true)
    protected String reports;
    @XmlElement(required = true)
    protected Configuration.Pool pool;

    /**
     * Gets the value of the modules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModules() {
        return modules;
    }

    /**
     * Sets the value of the modules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModules(String value) {
        this.modules = value;
    }

    /**
     * Gets the value of the database property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabase() {
        return database;
    }

    /**
     * Sets the value of the database property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabase(String value) {
        this.database = value;
    }

    /**
     * Gets the value of the reports property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReports() {
        return reports;
    }

    /**
     * Sets the value of the reports property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReports(String value) {
        this.reports = value;
    }

    /**
     * Gets the value of the pool property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration.Pool }
     *     
     */
    public Configuration.Pool getPool() {
        return pool;
    }

    /**
     * Sets the value of the pool property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration.Pool }
     *     
     */
    public void setPool(Configuration.Pool value) {
        this.pool = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="timeouts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="onetask" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="awaitTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "size",
        "timeouts"
    })
    public static class Pool {

        protected int size;
        @XmlElement(required = true)
        protected Configuration.Pool.Timeouts timeouts;

        /**
         * Gets the value of the size property.
         * 
         */
        public int getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         */
        public void setSize(int value) {
            this.size = value;
        }

        /**
         * Gets the value of the timeouts property.
         * 
         * @return
         *     possible object is
         *     {@link Configuration.Pool.Timeouts }
         *     
         */
        public Configuration.Pool.Timeouts getTimeouts() {
            return timeouts;
        }

        /**
         * Sets the value of the timeouts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Configuration.Pool.Timeouts }
         *     
         */
        public void setTimeouts(Configuration.Pool.Timeouts value) {
            this.timeouts = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="onetask" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="awaitTermination" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "onetask",
            "awaitTermination"
        })
        public static class Timeouts {

            protected int onetask;
            protected int awaitTermination;

            /**
             * Gets the value of the onetask property.
             * 
             */
            public int getOnetask() {
                return onetask;
            }

            /**
             * Sets the value of the onetask property.
             * 
             */
            public void setOnetask(int value) {
                this.onetask = value;
            }

            /**
             * Gets the value of the awaitTermination property.
             * 
             */
            public int getAwaitTermination() {
                return awaitTermination;
            }

            /**
             * Sets the value of the awaitTermination property.
             * 
             */
            public void setAwaitTermination(int value) {
                this.awaitTermination = value;
            }

        }

    }

}
